name: Generate Contribution Snake

on:
  schedule:
    # Run every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - uses: actions/checkout@v2
      
      # Generate the snake SVG
      - uses: Platane/snk@master
        with:
          github_user_name: amruthak2003
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Publish the SVG to the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
